---

version: '2'
services:
  redis:
    image: redis:latest
    volumes:
      - ./redis:/data

  app:
    build: ./.docker/
    command: /opt/run.sh
    env_file:
      - ./app.env
    depends_on:
      - redis
    ports:
      - "8000:8000"
      - "3022:22" # for debug via ssh
    volumes:
      - "./admitad_test:/opt/django"

volumes:
  app:
    driver: local
  redis:
    driver: local